### ISSUE TITLE
Select Text Editor

### ISSUE THREAD

**Issue by i486** [leonid20000/OdinRunes#1]
It would be great if you could add preferred text editor options to OdinRunes. Currently, it only opens Notepad, while I want to test this on Notepad++

I could change my *.txt file association to Notepad++, but I really don't want to, lol.

Anyways, very cool, unique program.

**Comment by leonid20000** [comment]
@i486 Thank you for your feedback, great suggestion indeed. Will include that in future updates. Until then you can easily achieve your desired behavior as follows:

![Using OdinRunes with your favorite editor](https://github.com/leonid20000/OdinRunes/assets/26918192/e18b542c-1d74-4134-a592-64fb127ea489)

 Just save your chat with your desired extension (for example chatplusplus) and set the default application for your desired extension to your desired editor.
